Repository skaut/Skautske-hospodareni, pull requests merged in 2019-11, with the labels that each got.

#1091 Zobrazit všechny nezrušené akce
  app/AccountancyModule/EventModule/presenters/DefaultPresenter.php
Labels: Event, PR - Bugfix

#1090 úprava tabulky pro harmonizovanou spotřebu
  app/AccountancyModule/TravelModule/templates/Vehicle/new.latte
Labels: Travel

#1104 default grid sort
  app/AccountancyModule/CampModule/presenters/DefaultPresenter.php
  app/AccountancyModule/EventModule/presenters/DefaultPresenter.php
Labels: Camp, Event

#1105 small fixes
  app/AccountancyModule/CampModule/presenters/ParticipantPresenter.php
  app/AccountancyModule/EventModule/presenters/BasePresenter.php
  app/AccountancyModule/EventModule/presenters/ParticipantPresenter.php
  app/AccountancyModule/Traits/ParticipantTrait.php
  app/model/Skautis/ParticipantRepository.php
Labels: PR - Bugfix

#1116 use transaction_id as a string
  app/model/Payment/Payment/Transaction.php
  migrations/2019/Version20191117210220.php
  tests/integration/Infrastructure/Repositories/Payment/PaymentRepositoryTest.php
  tests/unit/BankServiceTest.php
Labels: PR - Bugfix

#1117 show payment group name on paired payment
  app/AccountancyModule/PaymentModule/presenters/BankAccountsPresenter.php
  app/AccountancyModule/PaymentModule/templates/BankAccounts/detail.latte
Labels: Payments

#1115 fix type
  app/model/Skautis/ParticipantRepository.php
Labels: PR - Bugfix

#1106 zero participant income
  app/AccountancyModule/CampModule/presenters/CashbookPresenter.php
  app/model/Participant/Exception/ZeroParticipantIncome.php
  app/model/Participant/ReadModel/QueryHandlers/CampParticipantIncomeQueryHandler.php
Labels: PR - Bugfix

#1131 check if command is null
  app/AccountancyModule/TravelModule/presenters/DefaultPresenter.php
Labels: PR - Bugfix, Travel

#1132 Oprava resetování filtrů při změně řazení
  app/AccountancyModule/Components/templates/datagrid.latte
  app/AccountancyModule/Grids/GridFactory.php
Labels: PR - Bugfix
