Repository skaut/Skautske-hospodareni, pull requests merged in 2019-12, with the labels that each got.

#1143 Oprava zakládání účastníků bez vyplnění data narození
  app/model/Skautis/ParticipantRepository.php
Labels: PR - Bugfix, Participants

#1118 Změna SMTP hesla
  app/AccountancyModule/PaymentModule/components/SmtpAddForm.php
  app/AccountancyModule/PaymentModule/components/SmtpUpdateForm.php
  app/AccountancyModule/PaymentModule/components/templates/SmtpAddForm.latte
  app/AccountancyModule/PaymentModule/components/templates/SmtpUpdateForm.latte
  app/AccountancyModule/PaymentModule/factories/ISmtpAddFormFactory.php
  app/AccountancyModule/PaymentModule/factories/ISmtpUpdateFormFactory.php
  app/AccountancyModule/PaymentModule/presenters/MailPresenter.php
  app/AccountancyModule/PaymentModule/templates/Mail/default.latte
  app/model/Payment/Commands/UpdateMailPassword.php
  app/model/Payment/Handlers/MailCredentials/UpdateMailPasswordHandler.php
  app/model/Payment/MailCredentials.php
Labels: Payments

#1147 Export dokladů banky v hromadném exportu
  app/model/Cashbook/ReadModel/QueryHandlers/Pdf/SheetChitsGenerator.php
Labels: Cashbook

#1146 redirect of vehicle presenter
  app/AccountancyModule/TravelModule/presenters/VehiclePresenter.php
Labels: PR - Bugfix, Travel

#1061 Akce a tábory v novém designu
  app/AccountancyModule/AccountancyHelpers.php
  app/AccountancyModule/CampModule/presenters/BudgetPresenter.php
  app/AccountancyModule/CampModule/presenters/DetailPresenter.php
  app/AccountancyModule/CampModule/templates/@campsGrid.latte
  app/AccountancyModule/CampModule/templates/Budget/default.latte
  app/AccountancyModule/CampModule/templates/Detail/default.latte
  app/AccountancyModule/CampModule/templates/header.latte
  app/AccountancyModule/EventModule/components/templates/FunctionsControl.latte
  app/AccountancyModule/EventModule/presenters/EventPresenter.php
  app/AccountancyModule/EventModule/presenters/PrivilegesPresenter.php
  app/AccountancyModule/EventModule/templates/Event/default.latte
  app/AccountancyModule/EventModule/templates/Event/logs.latte
  app/AccountancyModule/EventModule/templates/Privileges/default.latte
  app/AccountancyModule/EventModule/templates/header.latte
  frontend/icons.ts
Labels: Camp, Event, Refactoring

#1164 Oprava neaktivního víkendu v datepickeru u akcí a cesťáků
  app/AccountancyModule/Components/FormControls/DateControl.php
  app/AccountancyModule/EventModule/templates/NewEvent/default.latte
  app/AccountancyModule/PaymentModule/components/GroupForm.php
  app/AccountancyModule/PaymentModule/components/MassAddForm.php
  app/AccountancyModule/PaymentModule/components/PaymentDialog.php
  app/AccountancyModule/PaymentModule/presenters/RepaymentPresenter.php
  frontend/ts/datePicker.ts
Labels: PR - Bugfix

#1166 Explicitní označení date pickerů jako nepovinných
  app/AccountancyModule/PaymentModule/components/MassAddForm.php
  app/AccountancyModule/PaymentModule/presenters/RepaymentPresenter.php
Labels: PR - Bugfix

#1163 Přidat jednotku do excelového exportu účastníků výpravy
  app/model/Excel/ExcelService.php
Labels: Event, Participants

#1177 Použití balíčku místo vlastního Sentry Breadcrumbs Monolog handleru
  app/config/sentry.neon
  app/model/Infrastructure/Log/Sentry/BreadcrumbsMonologHandler.php
  composer.json
  composer.lock
  tests/unit/Infrastructure/Log/Sentry/BreadcrumbsMonologHandlerTest.php
Labels: Refactoring

#1175 Oprava názvu scan souboru
  .docs/tipy-pro-testovani.md
  app/model/Common/FilePath.php
  tests/integration/Infrastructure/Services/Common/FlysystemScanStorageTest.php
  tests/unit/Common/FilePathTest.php
Labels: PR - Bugfix

#1178 Nahrazení arachne/codeception za contributte/codeception
  composer.json
  composer.lock
  tests/integration.suite.yml
Labels: Refactoring

#1180 check mail is not null
  app/AccountancyModule/PaymentModule/presenters/MailPresenter.php
Labels: PR - Bugfix
