Repository skaut/Skautske-hospodareni, pull requests merged in 2019-09, with the labels that each got.

#999 Řazení plateb + přesun přidávání/úpravy plateb do modálu
  app/AccountancyModule/AccountancyHelpers.php
  app/AccountancyModule/CampModule/CampListDataSource.php
  app/AccountancyModule/Components/DataGrid.php
  app/AccountancyModule/Components/templates/datagrid.latte
  app/AccountancyModule/EventModule/EventListDataSource.php
  app/AccountancyModule/Forms/VariableSymbolControl.php
  app/AccountancyModule/Grids/DataSource.php
  app/AccountancyModule/Grids/DtoListDataSource.php
  app/AccountancyModule/PaymentModule/components/PaymentDialog.php
  app/AccountancyModule/PaymentModule/components/PaymentList.php
  app/AccountancyModule/PaymentModule/components/templates/PaymentDialog.latte
  app/AccountancyModule/PaymentModule/components/templates/PaymentList.grid.latte
  app/AccountancyModule/PaymentModule/components/templates/PaymentList.latte
  app/AccountancyModule/PaymentModule/factories/IPaymentDialogFactory.php
  app/AccountancyModule/PaymentModule/factories/IPaymentListFactory.php
  app/AccountancyModule/PaymentModule/presenters/PaymentPresenter.php
  app/AccountancyModule/PaymentModule/templates/Payment/default.latte
  app/AccountancyModule/PaymentModule/templates/Payment/edit.latte
  app/model/Payment/Payment/State.php
  app/model/Payment/PaymentService.php
  app/model/Payment/VariableSymbol.php
  frontend/app.scss
  frontend/app.ts
  frontend/ts/DataGridExtension.ts
  frontend/ts/ModalExtension.ts
  frontend/ts/ajax.ts
  frontend/ts/netteForms.ts
  tests/_data/cleanup.sql
  tests/_support/Page/Payment.php
  tests/acceptance/PaymentCept.php
Labels: PR - Feature

#1023 Inicializace Bootstrap prvků ve snippetech
  frontend/app.ts
  frontend/ts/ajax.ts
  frontend/types/window.d.ts
  package.json
  webpack.config.js
  yarn.lock
Labels: PR - Bugfix

#996 Automatické odebrání vybraného emailu u skupiny při jeho smazání
  app/model/Infrastructure/Repositories/Payment/GroupRepository.php
  app/model/Infrastructure/Repositories/Payment/MailCredentialsRepository.php
  app/model/Payment/Commands/RemoveMailCredentials.php
  app/model/Payment/DomainEvents/MailCredentialsWasRemoved.php
  app/model/Payment/Group.php
  app/model/Payment/MailCredentials/MailProtocol.php
  app/model/Payment/Repositories/IGroupRepository.php
  app/model/Payment/Subscribers/GroupRemovedSubscriber.php
  app/model/Payment/Subscribers/MailCredentialsRemovedSubscriber.php
  tests/integration/Infrastructure/Repositories/Payment/MailCredentialsRepositoryTest.php
  tests/integration/Payment/Handlers/MailCredentials/RemoveMailCredentialsHandlerTest.php
  tests/integration/Payment/UseCases/RemoveGroupTest.php
  tests/integration/Payment/UseCases/RemoveMailCredentialsTest.neon
  tests/integration/Payment/UseCases/RemoveMailCredentialsTest.php
  tests/unit/User/ReadModel/QueryHandlers/EditableUnitsQueryHandlerTest.php
Labels: PR - Bugfix

#994 set backlink default value
  app/presenters/AuthPresenter.php
Labels: PR - Bugfix

#1038 Použití netteForms.js z vendor
  frontend/ts/netteForms.ts
  package.json
  yarn.lock
Labels: Refactoring

#1040 Odeslání formláře pro přidání/úpravu dokladu stiskem enter
  app/AccountancyModule/Components/templates/ChitForm.latte
  app/config/webloader.neon
  www/js/enter.js
Labels: PR - Bugfix

#1042 Oprava přehledu časopisů
  app/AccountancyModule/PaymentModule/presenters/JournalPresenter.php
  app/AccountancyModule/PaymentModule/templates/Journal/default.latte
  app/AccountancyModule/PaymentModule/templates/Payment/default.latte
  app/model/Payment/PaymentService.php
Labels: PR - Bugfix

#1055 Oprava datoveho typu ze skautisu
  app/model/Event/Factory/CampFactory.php
Labels: PR - Bugfix
