Repository skaut/Skautske-hospodareni, pull requests merged in 2020-04, with the labels that each got.

#1315 Oprava editace cesty
  app/AccountancyModule/TravelModule/Components/EditTravelDialog.php
Labels: PR - Bugfix

#1316 Cleanup závislostí
  app/Console/LintLatte.php
  composer.json
  composer.lock
Labels: Refactoring

#1318 Oprava staré migrace
  migrations/2019/Version20190321140458.php
Labels: PR - Bugfix

#1317 Abstrakce pro modální dialogy
  app/AccountancyModule/CampModule/Components/ExportDialog.php
  app/AccountancyModule/CampModule/Components/templates/ExportDialog.latte
  app/AccountancyModule/Components/Dialog.php
  app/AccountancyModule/Components/templates/Dialog.layout.latte
  app/AccountancyModule/EventModule/components/ExportDialog.php
  app/AccountancyModule/EventModule/components/templates/ExportDialog.latte
  app/AccountancyModule/PaymentModule/components/PaymentDialog.php
  app/AccountancyModule/PaymentModule/components/RemoveGroupDialog.php
  app/AccountancyModule/PaymentModule/components/SmtpUpdateForm.php
  app/AccountancyModule/PaymentModule/components/templates/PaymentDialog.latte
  app/AccountancyModule/PaymentModule/components/templates/RemoveGroupDialog.latte
  app/AccountancyModule/PaymentModule/components/templates/SmtpUpdateForm.latte
  app/AccountancyModule/TravelModule/Components/EditTravelDialog.php
  app/AccountancyModule/TravelModule/Components/templates/EditTravelDialog.latte
  tests/_support/Page/Payment.php
Labels: Refactoring

#1324 Oprava názvu dopravy v exportu cesťáku
  app/AccountancyModule/TravelModule/templates/Default/ex.command.latte
Labels: PR - Bugfix

#1323 Oprava kompatibility s Latte 2.7
  app/AccountancyModule/Components/Cashbook/templates/ChitListControl.latte
Labels: Refactoring

#1332 Nové testy pro helpery
  app/AccountancyModule/AccountancyHelpers.php
  tests/unit/AccountancyHelpersTest.php
Labels: Refactoring

#1330 Přidáno jméno uživatele, který dokončil platbu
  app/AccountancyModule/PaymentModule/components/templates/PaymentList.grid.latte
  app/AccountancyModule/templates/accessDenied.latte
  app/model/Bank/BankService.php
  app/model/DTO/Payment/Payment.php
  app/model/DTO/Payment/PaymentFactory.php
  app/model/Payment/Payment.php
  app/model/Payment/PaymentService.php
  migrations/2020/Version20200410190351.php
  tests/integration/Payment/UseCases/PaymentCompletedEmailTest.php
  tests/integration/PaymentServiceTest.neon
  tests/unit/Payment/PaymentTest.php
Labels: Payments

#1338 Oprava zobrazení
  app/AccountancyModule/CampModule/templates/header.latte
  app/AccountancyModule/Components/Cashbook/templates/ChitListControl.latte
  app/AccountancyModule/EventModule/templates/header.latte
  app/AccountancyModule/UnitAccountModule/templates/header.latte
  app/templates/@layout2.latte
  frontend/app.scss
Labels: PR - Bugfix

#1339 fix year separator
  app/AccountancyModule/Components/Cashbook/templates/ChitListControl.latte
Labels: Cashbook, PR - Bugfix

#1331 Zobrazení chybové stránky místo přesměrování
  app/AccountancyModule/CampModule/presenters/BasePresenter.php
  app/AccountancyModule/EventModule/presenters/BasePresenter.php
  app/AccountancyModule/EventModule/presenters/NewEventPresenter.php
  app/AccountancyModule/PaymentModule/presenters/BankAccountsPresenter.php
  app/AccountancyModule/PaymentModule/presenters/BasePresenter.php
  app/AccountancyModule/PaymentModule/presenters/GroupPresenter.php
  app/AccountancyModule/PaymentModule/presenters/JournalPresenter.php
  app/AccountancyModule/PaymentModule/presenters/MailPresenter.php
  app/AccountancyModule/PaymentModule/presenters/PaymentPresenter.php
  app/AccountancyModule/TravelModule/presenters/ContractPresenter.php
  app/AccountancyModule/TravelModule/presenters/DefaultPresenter.php
  app/AccountancyModule/TravelModule/presenters/VehiclePresenter.php
  app/AccountancyModule/UnitAccountModule/presenters/BasePresenter.php
  app/AccountancyModule/presenters/BasePresenter.php
  app/AccountancyModule/templates/accessDenied.latte
  docker-compose.override.yml
Labels: PR - Feature

#1335 Migrace cashbookId z int na UUIDv4
  app/model/Cashbook/Cashbook/CashbookId.php
  migrations/2020/Version20200411105206.php
  tests/integration/Cashbook/CashbookIntegrationTest.php
  tests/integration/Cashbook/Handlers/MoveChitsToDifferentCashbookHandlerTest.php
  tests/integration/Cashbook/ReadModel/QueryHandlers/ChitListQueryHandlerTest.php
  tests/integration/Infrastructure/Repositories/Cashbook/CashbookRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Cashbook/UnitRepositoryTest.php
  tests/unit/Cashbook/Cashbook/CashbookIdTest.php
  tests/unit/Cashbook/CashbookTest.php
  tests/unit/Cashbook/Handlers/CashbookHandlersTest.php
  tests/unit/Cashbook/Handlers/CreateCashbookHandlerTest.php
  tests/unit/Cashbook/ReadModel/CategoryPairsQueryHandlerTest.php
  tests/unit/Cashbook/ReadModel/ChitQueryHandlerTest.php
  tests/unit/Cashbook/ReadModel/FinalBalanceQueryHandlerTest.php
  tests/unit/Cashbook/ReadModel/FinalRealBalanceQueryHandlerTest.php
  tests/unit/Cashbook/Repositories/CategoryRepositoryTest.php
  tests/unit/Cashbook/UnitTest.php
Labels: Refactoring

#1344 Odebrání upozornění
  app/AccountancyModule/EventModule/templates/Event/default.latte
  app/templates/Tutorial/event.latte
Labels: Event

#1342 Zvýraznění tlačítka uzavřít akci
  app/AccountancyModule/EventModule/presenters/EventPresenter.php
  app/AccountancyModule/EventModule/templates/Event/default.latte
Labels: Event

#1345 Příprava pro latte 2.7
  app/AccountancyModule/StatisticsModule/templates/Default/default.latte
  app/model/Export/templates/cashbook.latte
  app/model/Export/templates/chitlist.latte
Labels: Refactoring

#1261 Sjednocení mapování a databáze
  .github/workflows/main.yml
  app/config/model/doctrine.neon
  app/model/Budget/Category.php
  app/model/Cashbook/Cashbook/Chit.php
  app/model/Cashbook/Category.php
  app/model/Cashbook/Category/ObjectType.php
  app/model/Infrastructure/Types/MoneyType.php
  app/model/Logger/LogEntry.php
  app/model/Participant/Payment.php
  migrations/2020/Version20200214111513.php
  migrations/2020/Version20200214114359.php
  migrations/2020/Version20200214130535.php
  migrations/2020/Version20200406114332.php
  tests/integration/Cashbook/CashbookIntegrationTest.php
  tests/integration/Infrastructure/Repositories/Travel/CommandRepositoryTest.php
Labels: PR - DB change, Refactoring

#1347 Seskupení tlačítek
  app/AccountancyModule/PaymentModule/templates/Payment/default.latte
  tests/_support/Page/Payment.php
Labels: Payments

#1336 Účastníci v novém designu
  app/AccountancyModule/CampModule/presenters/ParticipantPresenter.php
  app/AccountancyModule/CampModule/templates/Participant/default.latte
  app/AccountancyModule/Components/Participants/EditParticipantDialog.php
  app/AccountancyModule/Components/Participants/ParticipantList.php
  app/AccountancyModule/Components/Participants/PersonPicker.php
  app/AccountancyModule/Components/Participants/templates/EditParticipantDialog.latte
  app/AccountancyModule/Components/Participants/templates/ParticipantList.js.latte
  app/AccountancyModule/Components/Participants/templates/ParticipantList.latte
  app/AccountancyModule/Components/Participants/templates/PersonPicker.latte
  app/AccountancyModule/EventModule/presenters/ParticipantPresenter.php
  app/AccountancyModule/EventModule/templates/Participant/default.latte
  frontend/icons.ts
  frontend/ts/ajax.ts
  frontend/ts/checkboxes.ts
  phpcs.xml
Labels: PR - Feature

#1350 fix participants mass edit
  app/AccountancyModule/Components/Participants/ParticipantList.php
Labels: PR - Bugfix, Participants

#1351 Sloučení exportovacích tlačítek pro pokladní knihu
  app/AccountancyModule/Components/Cashbook/templates/ChitListControl.topPanel.latte
Labels: Cashbook, Changelog

#1355 Odebrání duplicitních *
  app/AccountancyModule/TravelModule/Components/EditTravelDialog.php
Labels: PR - Bugfix
