Repository skaut/Skautske-hospodareni, pull requests merged in 2020-11, with the labels that each got.

#1503 Přidání Google SDK klienta
  composer.json
  composer.lock
Labels: Refactoring

#1504 Oprava řazení plateb podle jména
  app/AccountancyModule/CampModule/Components/ExportDialog.php
  app/AccountancyModule/EventModule/components/ExportDialog.php
  app/AccountancyModule/PaymentModule/components/PaymentList.php
  app/model/Payment/PaymentService.php
  app/model/Services/Language.php
  app/model/Skautis/MemberRepository.php
  app/model/Skautis/ParticipantRepository.php
  tests/unit/Services/LanguageTest.php
Labels: PR - Bugfix

#1505 Nastavení google credentials při deploymentu
  .github/workflows/main.yml
  app/AccountancyModule/PaymentModule/templates/Mail/default.latte
  app/config/config.production.local.neon
  app/config/config.test.local.neon
  build.xml
Labels: PR - Bugfix

#1508 Oprava přidávání Google účtů
  app/model/Google/GoogleService.php
Labels: PR - Bugfix

#1509 Oprava odchytávání výjimky při nevyplněném emailu u skupiny plateb
  app/model/Payment/MailingService.php
Labels: PR - Bugfix

#1513 Povolit přidat skeny k uzavřené pokladní knize
  app/AccountancyModule/Components/Cashbook/ChitScanControl.php
Labels: Cashbook

#1477 Přidání plateb pro vzdělávací akce
  app/AccountancyModule/PaymentModule/presenters/AddEducationParticipantsPresenter.php
  app/AccountancyModule/PaymentModule/presenters/CreateEducationGroupPresenter.php
  app/AccountancyModule/PaymentModule/presenters/SelectEducationForGroupPresenter.php
  app/AccountancyModule/PaymentModule/templates/AddEducationParticipants/default.latte
  app/AccountancyModule/PaymentModule/templates/CreateEducationGroup/default.latte
  app/AccountancyModule/PaymentModule/templates/GroupList/default.latte
  app/AccountancyModule/PaymentModule/templates/Payment/default.latte
  app/AccountancyModule/PaymentModule/templates/SelectEducationForGroup/default.latte
  app/model/Common/Repositories/IParticipantRepository.php
  app/model/Event/Education.php
  app/model/Event/Factory/EducationFactory.php
  app/model/Event/ReadModel/Queries/EducationListQuery.php
  app/model/Event/ReadModel/QueryHandlers/EducationListQueryHandler.php
  app/model/Event/SkautisEducationId.php
  app/model/Participant/Factory/ParticipantFactory.php
  app/model/Participant/Payment/EventType.php
  app/model/Participant/ReadModel/Queries/EducationParticipantListQuery.php
  app/model/Participant/ReadModel/QueryHandlers/EducationParticipantListQueryHandler.php
  app/model/Payment/Group/SkautisEntity.php
  app/model/Payment/Group/Type.php
  app/model/Payment/ReadModel/Queries/EducationsWithoutGroupQuery.php
  app/model/Payment/ReadModel/QueryHandlers/EducationsWithoutGroupQueryHandler.php
  app/model/Skautis/ParticipantRepository.php
  frontend/icons.ts
  tests/_support/SkautisTest.php
  tests/integration/Skautis/ParticipantRepositoryTest.php
  tests/integration/fixtures/ParticipantRepository/findByEducation_all.json
Labels: Education, Payments

#1388 Nahrazení Kdyby/Doctrine za Nettrine DBAL + vlastní EntityManagerFactory
  app/AccountancyModule/CampModule/presenters/ParticipantPresenter.php
  app/AccountancyModule/Components/BaseControl.php
  app/AccountancyModule/Components/Participants/ParticipantList.php
  app/AccountancyModule/EventModule/presenters/ParticipantPresenter.php
  app/AccountancyModule/Forms/CustomControlFactories.php
  app/AccountancyModule/Forms/VariableSymbolControl.php
  app/AccountancyModule/Grids/DtoListDataSource.php
  app/AccountancyModule/PaymentModule/presenters/PaymentPresenter.php
  app/AccountancyModule/presenters/BasePresenter.php
  app/Bootstrap4FormRenderer.php
  app/config/model/doctrine.neon
  app/model/Base/AggregateId.php
  app/model/Budget/Category.php
  app/model/Cashbook/Cashbook.php
  app/model/Cashbook/Cashbook/CashbookType.php
  app/model/Cashbook/Cashbook/Chit.php
  app/model/Cashbook/Category.php
  app/model/Cashbook/ReadModel/CategoryTotalsCalculator.php
  app/model/Cashbook/Unit.php
  app/model/Google/OAuth.php
  app/model/Google/ReadModel/QueryHandlers/UnitOAuthListQueryHandler.php
  app/model/Google/Repositories/IGoogleRepository.php
  app/model/Infrastructure/EntityManagerFactory.php
  app/model/Infrastructure/EnumListener.php
  app/model/Infrastructure/Repositories/Google/GoogleRepository.php
  app/model/Infrastructure/Repositories/Payment/GroupRepository.php
  app/model/Infrastructure/Types/OAuthIdType.php
  app/model/Payment/Group.php
  app/model/Payment/Payment.php
  app/model/Travel/Command.php
  app/model/Travel/Vehicle.php
  app/router/RouterFactory.php
  build.xml
  composer.json
  composer.lock
  migrations/2020/Version20201126130912.php
  phpstan.neon
  tests/integration/Infrastructure/Repositories/Mail/GoogleRepositoryTest.php
Labels: Refactoring

#1518 Registrace dvou používaných ORM příkazů do konzole
  app/config/model/doctrine.neon
Labels: PR - Bugfix
