Repository skaut/Skautske-hospodareni, pull requests merged in 2020-01, with the labels that each got.

#1189 Oprava data provideru v AmountTest::testIsUsingFormula()
  tests/unit/Cashbook/Cashbook/AmountTest.php
Labels: PR - Bugfix

#1206 Odebrána nepotřebná kontrola, zda je oddíl u vozidla pod střediskem
  app/model/Travel/Vehicle.php
  app/model/Unit/Services/Unit.php
  tests/integration/Infrastructure/Repositories/Travel/VehicleRepositoryTest.php
  tests/unit/Travel/VehicleTest.php
Labels: PR - Bugfix

#1207 Oprava špatné odchytávané výjimky při kontrole smazané jednotky
  app/AccountancyModule/TravelModule/presenters/VehiclePresenter.php
Labels: PR - Bugfix

#1208 Oprava dat pražských účastníků v exportu akcí
  app/model/Event/ReadModel/QueryHandlers/Excel/ExportEventsHandler.php
Labels: PR - Bugfix

#1209 Přidána chybová hláška pro pole pro zadání data splatnosti
  app/AccountancyModule/Components/FormControls/DateControl.php
Labels: PR - Bugfix

#1210 Rozdělení táborových vratek pro děti a dospělé
  app/model/Cashbook/ICategory.php
  app/model/Cashbook/ParticipantType.php
  app/model/Cashbook/ReadModel/CategoryTotalsCalculator.php
  app/model/Cashbook/ReadModel/QueryHandlers/CategoryListQueryHandler.php
  app/model/Export/ExportService.php
  app/model/Export/templates/campReport.latte
  migrations/2020/Version20200112173514.php
  tests/unit/Cashbook/ReadModel/CategoryTotalsCalculatorTest.php
Labels: Camp

#1222 Oprava JS na "velkých stránkách"
  frontend/ts/ajax.ts
Labels: PR - Bugfix

#1223 Odebrána nepoužívaná metoda IUnitRepository::findAsStdClass()
  app/model/Skautis/UnitRepository.php
  app/model/Unit/Repositories/IUnitRepository.php
Labels: Refactoring

#1231 Automatické dohledávání entit z agregátu v testech
  tests/_support/IntegrationTest.php
  tests/integration/Cashbook/CashbookIntegrationTest.php
  tests/integration/Cashbook/Handlers/MoveChitsToDifferentCashbookHandlerTest.php
  tests/integration/Cashbook/Handlers/Unit/CreateCashbookHandlerTest.php
  tests/integration/Cashbook/Handlers/Unit/CreateUnitHandlerTest.php
  tests/integration/Cashbook/ReadModel/QueryHandlers/ChitListQueryHandlerTest.php
  tests/integration/Infrastructure/Repositories/Budget/CategoryRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Cashbook/CashbookRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Cashbook/StaticCategoryRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Cashbook/UnitRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Logger/LogEntryRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Payment/BankAccountRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Payment/GroupRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Payment/MailCredentialsRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Payment/PaymentRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Travel/CommandRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Travel/ContractRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Travel/VehicleRepositoryTest.php
  tests/integration/Payment/BankAccountServiceTest.php
  tests/integration/Payment/BankServiceTest.php
  tests/integration/Payment/Handlers/MailCredentials/CreateMailCredentialsHandlerTest.php
  tests/integration/Payment/Handlers/MailCredentials/RemoveMailCredentialsHandlerTest.php
  tests/integration/Payment/ReadModel/QueryHandlers/CountGroupsWithBankAccountQueryHandlerTest.php
  tests/integration/Payment/ReadModel/QueryHandlers/PairedPaymentsQueryHandlerTest.php
  tests/integration/Payment/UseCases/LastPairingInvalidationTest.php
  tests/integration/Payment/UseCases/PaymentCompletedEmailTest.php
  tests/integration/Payment/UseCases/RemoveGroupTest.php
  tests/integration/Payment/UseCases/RemoveMailCredentialsTest.php
  tests/integration/PaymentServiceTest.php
Labels: Refactoring

#1236 Zarovnání čísel doprava
  app/AccountancyModule/CampModule/templates/Detail/default.latte
  app/AccountancyModule/EventModule/templates/Event/default.latte
Labels: Camp, Event

#1237 Zachycení neoprávněného přístupu k táboru a přesměrování místo 500
  app/AccountancyModule/CampModule/presenters/BasePresenter.php
Labels: PR - Bugfix

#1242 Kompilace SASS -> CSS přes Webpack
  .docs/nastroje.md
  frontend/app.scss
  frontend/app.ts
  frontend/scss/pikaday.scss
  package.json
  postcss.config.js
  webpack.config.js
  yarn.lock
Labels: Refactoring

#1239 Oprava kontroly, zda lze zrušit akci
  app/AccountancyModule/EventModule/presenters/DefaultPresenter.php
  app/model/Auth/Resources/Event.php
Labels: PR - Bugfix

#1240 Oprava zobrazování labelů
  app/AccountancyModule/AccountancyHelpers.php
  app/AccountancyModule/EventModule/templates/Default/@eventsGrid.latte
Labels: PR - Bugfix

#1241 Oprava kompatibility s Latte 2.6 + kontrola Latte šablon v CI
  .github/workflows/main.yml
  app/AccountancyModule/PaymentModule/components/templates/PairButton.latte
  app/Console/LintLatte.php
  app/config/config.neon
  composer.json
  composer.lock
  phpcs.xml
Labels: Refactoring

#1244 Opravena kontrola CS v Github Actions
  .github/workflows/main.yml
Labels: PR - Bugfix

#1226 Odstranění stavu odesláno + počítadlo odeslaných emailů
  app/AccountancyModule/AccountancyHelpers.php
  app/AccountancyModule/Components/templates/DataGrid.layout.latte
  app/AccountancyModule/PaymentModule/components/GroupProgress.php
  app/AccountancyModule/PaymentModule/components/PaymentList.php
  app/AccountancyModule/PaymentModule/components/templates/GroupProgress.latte
  app/AccountancyModule/PaymentModule/components/templates/PaymentList.grid.latte
  app/AccountancyModule/PaymentModule/presenters/GroupListPresenter.php
  app/AccountancyModule/PaymentModule/presenters/PaymentPresenter.php
  app/AccountancyModule/PaymentModule/templates/GroupList/default.latte
  app/AccountancyModule/PaymentModule/templates/Payment/default.latte
  app/model/DTO/Payment/Payment.php
  app/model/DTO/Payment/PaymentFactory.php
  app/model/Infrastructure/Repositories/Payment/PaymentRepository.php
  app/model/Payment/Handlers/Mailing/SendPaymentInfoHandler.php
  app/model/Payment/MailingService.php
  app/model/Payment/Payment.php
  app/model/Payment/Payment/SentEmail.php
  app/model/Payment/Payment/State.php
  app/model/Payment/Summary.php
  migrations/2020/Version20200101231338.php
  tests/acceptance/PaymentCept.php
  tests/integration/Infrastructure/Repositories/Payment/PaymentRepositoryTest.php
  tests/unit/Payment/PaymentTest.php
Labels: PR - Feature
