Repository skaut/Skautske-hospodareni, pull requests merged in 2020-05, with the labels that each got.

#1354 Oprava drobností v pokladní knize
  app/AccountancyModule/Components/Cashbook/ChitListControl.php
  app/AccountancyModule/Components/Cashbook/templates/ChitListControl.latte
  app/AccountancyModule/Components/Cashbook/templates/ChitListControl.topPanel.latte
  app/AccountancyModule/Components/Cashbook/templates/MoveChitsDialog.latte
Labels: PR - Bugfix

#1233 Github Actions jako hlavní CI
  .docs/jak-na-pull-request.md
  .github/workflows/known_hosts
  .github/workflows/main.yml
  .github/workflows/setup_ssh.sh
  README.md
  app/config/config.production.local.neon
  app/config/config.test.local.neon
  build.xml
  tests/Helper/WaitForDb.php
  tests/acceptance.suite.yml
  tests/integration.suite.yml
  wercker.yml
Labels: In progress

#1375 Přeleštění Github Actions deploymentu (Yarn cache + úpravy v outputu)
  .github/workflows/main.yml
  build.xml
Labels: Refactoring

#1381 Oprava názvu
  app/AccountancyModule/Components/Cashbook/templates/ChitScanControl.latte
  app/AccountancyModule/TravelModule/Components/templates/RoadworthyControl.latte
  app/model/Cashbook/ReadModel/QueryHandlers/CashbookScansQueryHandler.php
  app/model/Common/FilePath.php
Labels: PR - Bugfix

#1382 Oprava hromadného zaškrtávání checkboxů v evidenci plateb
  app/AccountancyModule/Components/Cashbook/templates/ChitListControl.latte
Labels: Cashbook, PR - Bugfix

#1383 Oprava počítání plateb bez odeslaného emailu
  app/AccountancyModule/PaymentModule/presenters/PaymentPresenter.php
  app/AccountancyModule/PaymentModule/templates/Payment/default.latte
Labels: PR - Bugfix

#1384 Oprava hromadné úpravy účastníků
  app/AccountancyModule/Components/Participants/ParticipantList.php
Labels: PR - Bugfix

#1385 Oprava seznamu účastníků
  .github/workflows/main.yml
  app/AccountancyModule/Components/Participants/templates/ParticipantList.latte
Labels: PR - Bugfix
