Repository skaut/Skautske-hospodareni, pull requests merged in 2020-03, with the labels that each got.

#1262 Přesun seznamu účastníků do komponenty
  app/AccountancyModule/CampModule/presenters/ParticipantPresenter.php
  app/AccountancyModule/CampModule/templates/Participant/default.latte
  app/AccountancyModule/Components/Participants/ParticipantList.php
  app/AccountancyModule/Components/Participants/PersonPicker.php
  app/AccountancyModule/Components/Participants/templates/ParticipantList.js.latte
  app/AccountancyModule/Components/Participants/templates/ParticipantList.latte
  app/AccountancyModule/Components/Participants/templates/PersonPicker.latte
  app/AccountancyModule/EventModule/presenters/ParticipantPresenter.php
  app/AccountancyModule/EventModule/templates/Participant/default.latte
  app/AccountancyModule/Factories/Participants/IParticipantListFactory.php
  app/AccountancyModule/Traits/ParticipantTrait.php
  app/model/DTO/Participant/UpdateParticipant.php
  app/model/Participant/ParticipantService.php
  app/templateBlocks/inline-num-edit.latte
  app/templateBlocks/inline-price-edit.latte
  app/templateBlocks/participants/js.latte
  app/templateBlocks/participants/participant.latte
Labels: Camp, Event, Participants

#1287 Oprava textu submitu při editaci platby
  app/AccountancyModule/PaymentModule/components/PaymentDialog.php
Labels: PR - Bugfix

#1288 Aktualizace deprecated syntaxe v Latte
  app/AccountancyModule/CampModule/templates/Budget/default.latte
Labels: Refactoring

#1291 PHP 7.4
  .docs/instalace.md
  .github/workflows/main.yml
  app/model/Payment/ReadModel/QueryHandlers/CountGroupsWithBankAccountQueryHandler.php
  composer.json
  composer.lock
  docker-compose.yml
  phpstan.neon
  tests/_hacks/SoapCodeTransform.php
  tests/_support/SkautisTest.php
  tests/_support/WebServiceWithInterception.php
  wercker.yml
Labels: Refactoring

#1296 MySQL 8 v Dockeru a dokumentaci
  .docs/instalace.md
  docker-compose.yml
Labels: PR - Bugfix

#1297 Použití enumu pro typ dopravy místo entity
  app/AccountancyModule/TravelModule/Components/CommandForm.php
  app/AccountancyModule/TravelModule/Components/EditTravelDialog.php
  app/AccountancyModule/TravelModule/presenters/DefaultPresenter.php
  app/AccountancyModule/TravelModule/templates/Default/detail.latte
  app/config/model/doctrine.neon
  app/model/DTO/Travel/Command.php
  app/model/DTO/Travel/CommandFactory.php
  app/model/DTO/Travel/TravelType.php
  app/model/DTO/Travel/TypeFactory.php
  app/model/Infrastructure/Repositories/Travel/TypeRepository.php
  app/model/Infrastructure/Types/TransportTypeListType.php
  app/model/Travel/Command.php
  app/model/Travel/Command/TransportTravel.php
  app/model/Travel/Command/TravelDetails.php
  app/model/Travel/ReadModel/Queries/TransportTypesQuery.php
  app/model/Travel/ReadModel/QueryHandlers/TransportTypesHandler.php
  app/model/Travel/Repositories/ITypeRepository.php
  app/model/Travel/Travel/TransportType.php
  app/model/Travel/Travel/Type.php
  app/model/Travel/TravelService.php
  migrations/2020/Version20200323131412.php
  tests/integration/Infrastructure/Repositories/Travel/CommandRepositoryTest.php
  tests/unit/DTO/Travel/Command/TravelFactoryTest.php
  tests/unit/Travel/CommandTest.php
Labels: Refactoring

#1299 Použití správné verze PHP na Lebedě při deploymentu
  build.xml
Labels: PR - Bugfix

#1300 Přidělání části LoginPanelu pro nepřihlášené uživatele
  app/AccountancyModule/Components/LoginPanel.php
  app/AccountancyModule/Components/templates/LoginPanel.latte
  app/templates/@layout2.latte
Labels: PR - Bugfix

#1303 Oprava schématu u cesťáků
  migrations/2020/Version20200330183259.php
Labels: PR - Bugfix
