Repository skaut/Skautske-hospodareni, pull requests merged in 2021-01, with the labels that each got.

#1569 Odebrání lookyman/nette-proxy
  app/config/config.neon
  app/model/Infrastructure/Skautis/LazyWebService.php
  app/model/Skautis/WebserviceFactory.php
  composer.json
  composer.lock
  tests/unit/Infrastructure/Skautis/LazyWebServiceTest.php
Labels: Refactoring

#1481 Refactoring Camp/Event presenteru v platbách
  app/AccountancyModule/PaymentModule/presenters/AddCampParticipantsPresenter.php
  app/AccountancyModule/PaymentModule/presenters/AddEventParticipantsPresenter.php
  app/AccountancyModule/PaymentModule/presenters/CampPresenter.php
  app/AccountancyModule/PaymentModule/presenters/CreateCampGroupPresenter.php
  app/AccountancyModule/PaymentModule/presenters/CreateEventGroupPresenter.php
  app/AccountancyModule/PaymentModule/presenters/EventPresenter.php
  app/AccountancyModule/PaymentModule/presenters/RegistrationPresenter.php
  app/AccountancyModule/PaymentModule/presenters/SelectCampForGroupPresenter.php
  app/AccountancyModule/PaymentModule/presenters/SelectEventForGroupPresenter.php
  app/AccountancyModule/PaymentModule/templates/AddCampParticipants/default.latte
  app/AccountancyModule/PaymentModule/templates/AddEventParticipants/default.latte
  app/AccountancyModule/PaymentModule/templates/CreateCampGroup/default.latte
  app/AccountancyModule/PaymentModule/templates/CreateEventGroup/default.latte
  app/AccountancyModule/PaymentModule/templates/Event/newGroup.latte
  app/AccountancyModule/PaymentModule/templates/GroupList/default.latte
  app/AccountancyModule/PaymentModule/templates/Payment/default.latte
  app/AccountancyModule/PaymentModule/templates/SelectCampForGroup/default.latte
  app/AccountancyModule/PaymentModule/templates/SelectEventForGroup/default.latte
Labels: Payments, Refactoring

#1570 Odebrání neexistujícího commandu z deploymentu
  build.xml
Labels: PR - Bugfix

#1567 Rozdělení registrace do samostatných presenterů
  app/AccountancyModule/PaymentModule/presenters/AddRegistrationMembersPresenter.php
  app/AccountancyModule/PaymentModule/presenters/CreateRegistrationGroupPresenter.php
  app/AccountancyModule/PaymentModule/templates/AddRegistrationMembers/default.latte
  app/AccountancyModule/PaymentModule/templates/CreateRegistrationGroup/default.latte
  app/AccountancyModule/PaymentModule/templates/GroupList/default.latte
  app/AccountancyModule/PaymentModule/templates/Payment/default.latte
Labels: Payments, Refactoring

#1579 Přidána poznámka o osobních údajích do bug šablony
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Refactoring
