Repository skaut/Skautske-hospodareni, pull requests merged in 2021-06, with the labels that each got.

#1675 Oprava vratek pro platby bez navázané osoby
  app/AccountancyModule/PaymentModule/presenters/RepaymentPresenter.php
  app/model/DTO/Payment/RepaymentCandidate.php
  app/model/DTO/Payment/RepaymentCandidateFactory.php
  app/model/Payment/ReadModel/QueryHandlers/RepaymentCandidateListQueryHandler.php
  tests/unit/Payment/ReadModel/QueryHandlers/RepaymentCandidateListQueryHandlerTest.php
Labels: PR - Bugfix, Payments

#1636 Přidání chybějící jednotky
  app/AccountancyModule/PaymentModule/components/GroupUnitControl.php
Labels: PR - Bugfix

#1678 Vyfiltrovat vzdělávací akce kde jsem v týmu
  app/model/Event/ReadModel/QueryHandlers/EducationListQueryHandler.php
Labels: Education, PR - Bugfix
