Repository skaut/Skautske-hospodareni, pull requests merged in 2021-11, with the labels that each got.

#1714 fix repayment type
  app/AccountancyModule/PaymentModule/presenters/RepaymentPresenter.php
Labels: PR - Bugfix

#1716 Oprava pouštění konzolových příkazů v rámci deploymentu
  app/config/config.neon
  build.xml
Labels: PR - Bugfix

#1739 Odebrání AutoDI
  app/config/components.neon
  app/config/config.neon
  composer.json
  composer.lock
Labels: Refactoring

#1752 Oprava špatně serializovaného seznamu dopravních prostředků
  app/model/Infrastructure/Types/TransportTypeListType.php
  app/model/Travel/Command.php
  app/model/Travel/TravelService.php
Labels: PR - Bugfix

#1753 Aktualizace cakephp/chronos
  composer.json
  composer.lock
Labels: Refactoring

#1755 Odebrání nepoužívané property `Payment::$email`
  app/model/Payment/Payment.php
  migrations/2021/Version20211121182733.php
  tests/integration/Infrastructure/Repositories/Payment/PaymentRepositoryTest.php
Labels: Refactoring

#1756 Aktualizace PHPStan na 1.2
  app/AccountancyModule/EventModule/presenters/CashbookPresenter.php
  app/model/Budget/Category.php
  app/model/Cashbook/Cashbook/Chit.php
  app/model/Cashbook/Cashbook/ChitScan.php
  app/model/Excel/Builders/CashbookWithCategoriesBuilder.php
  app/model/Payment/Group/Email.php
  app/model/Payment/Group/Unit.php
  app/model/Payment/Payment/EmailRecipient.php
  app/model/Payment/Payment/SentEmail.php
  app/model/Travel/Command.php
  app/model/Travel/Vehicle/RoadworthyScan.php
  composer.json
  composer.lock
  migrations/2021/Version20211121183832.php
  phpstan.neon
  tests/object-manager.php
Labels: Refactoring

#1769 Skrývání sloupců v platnách, přidanání sloupce Poznámka
  app/AccountancyModule/Components/templates/DataGrid.layout.latte
  app/AccountancyModule/Components/templates/datagrid.latte
  app/AccountancyModule/Grids/GridFactory.php
  app/AccountancyModule/PaymentModule/components/PaymentList.php
  app/AccountancyModule/PaymentModule/components/templates/PaymentList.grid.latte
  frontend/icons.ts
Labels: Payments
