Repository skaut/Skautske-hospodareni, pull requests merged in 2021-02, with the labels that each got.

#1581 Odebrání osob s nulovou platbou
  app/AccountancyModule/PaymentModule/presenters/AddRegistrationMembersPresenter.php
Labels: Payments

#1601 Oprava sbírání code coverage
  build.xml
Labels: PR - Bugfix

#1577 Payment submodules
  app/AccountancyModule/PaymentModule/CampModule/presenters/AddParticipantsPresenter.php
  app/AccountancyModule/PaymentModule/CampModule/presenters/CreateGroupPresenter.php
  app/AccountancyModule/PaymentModule/CampModule/presenters/SelectForGroupPresenter.php
  app/AccountancyModule/PaymentModule/CampModule/templates/AddParticipants/default.latte
  app/AccountancyModule/PaymentModule/CampModule/templates/CreateGroup/default.latte
  app/AccountancyModule/PaymentModule/CampModule/templates/SelectForGroup/default.latte
  app/AccountancyModule/PaymentModule/EducationModule/presenters/AddParticipantsPresenter.php
  app/AccountancyModule/PaymentModule/EducationModule/presenters/CreateGroupPresenter.php
  app/AccountancyModule/PaymentModule/EducationModule/presenters/SelectForGroupPresenter.php
  app/AccountancyModule/PaymentModule/EducationModule/templates/AddParticipants/default.latte
  app/AccountancyModule/PaymentModule/EducationModule/templates/CreateGroup/default.latte
  app/AccountancyModule/PaymentModule/EducationModule/templates/SelectForGroup/default.latte
  app/AccountancyModule/PaymentModule/EventModule/presenters/AddParticipantsPresenter.php
  app/AccountancyModule/PaymentModule/EventModule/presenters/CreateGroupPresenter.php
  app/AccountancyModule/PaymentModule/EventModule/presenters/SelectForGroupPresenter.php
  app/AccountancyModule/PaymentModule/EventModule/templates/AddParticipants/default.latte
  app/AccountancyModule/PaymentModule/EventModule/templates/CreateGroup/default.latte
  app/AccountancyModule/PaymentModule/EventModule/templates/SelectForGroup/default.latte
  app/AccountancyModule/PaymentModule/RegistrationModule/presenters/AddMembersPresenter.php
  app/AccountancyModule/PaymentModule/RegistrationModule/presenters/CreateGroupPresenter.php
  app/AccountancyModule/PaymentModule/RegistrationModule/presenters/JournalPresenter.php
  app/AccountancyModule/PaymentModule/RegistrationModule/templates/AddMembers/default.latte
  app/AccountancyModule/PaymentModule/RegistrationModule/templates/CreateGroup/default.latte
  app/AccountancyModule/PaymentModule/RegistrationModule/templates/Journal/default.latte
  app/AccountancyModule/PaymentModule/components/GroupForm.php
  app/AccountancyModule/PaymentModule/components/MassAddForm.php
  app/AccountancyModule/PaymentModule/templates/@groupBackLink.latte
  app/AccountancyModule/PaymentModule/templates/@layout.latte
  app/AccountancyModule/PaymentModule/templates/GroupList/default.latte
  app/AccountancyModule/PaymentModule/templates/Payment/default.latte
Labels: Refactoring

#1602 Blokování fixup! commitů před mergem
  .github/workflows/git.yml
Labels: Refactoring

#1582 Defaultní vybrání prvního emailu u hromadného importu plateb
  app/AccountancyModule/PaymentModule/components/MassAddForm.php
Labels: PR - Bugfix

#1604 Oprava error reportingu
  app/model/Infrastructure/Log/Sentry/UserContextEventProcessor.php
Labels: PR - Bugfix

#1609 Oprava špatného časového rozsahu při párování více skupin, kdy jedna nebyla párována
  app/model/Bank/BankService.php
  app/model/Bank/Fio/FioClient.php
  app/model/Payment/BankAccountService.php
  app/model/Payment/Fio/CachingClientDecorator.php
  app/model/Payment/Fio/IFioClient.php
  tests/unit/Bank/Fio/FioClientTest.php
  tests/unit/BankServiceTest.php
Labels: PR - Bugfix, Payments

#1606 Sjednocení názvu DB a ORM, odebrání unsigned
  app/model/Budget/Category.php
  app/model/Cashbook/Cashbook/Amount.php
  app/model/Cashbook/Cashbook/Category.php
  app/model/Cashbook/Cashbook/Chit.php
  app/model/Cashbook/Cashbook/ChitItem.php
  app/model/Cashbook/Category.php
  app/model/Cashbook/Category/ObjectType.php
  app/model/Logger/LogEntry.php
  app/model/Participant/Payment.php
  app/model/Payment/Group.php
  app/model/Payment/Group/PaymentDefaults.php
  app/model/Payment/Payment.php
  app/model/Payment/Payment/EmailRecipient.php
  app/model/Payment/Payment/SentEmail.php
  app/model/Payment/Payment/Transaction.php
  app/model/Travel/Command.php
  app/model/Travel/Command/Travel.php
  app/model/Travel/Command/TravelDetails.php
  app/model/Travel/Command/VehicleTravel.php
  app/model/Travel/Contract.php
  app/model/Travel/Passenger.php
  app/model/Travel/Vehicle.php
  migrations/2021/Version20210205181552.php
  migrations/2021/Version20210206080027.php
  migrations/2021/Version20210206085905.php
  tests/integration/Infrastructure/Repositories/Cashbook/StaticCategoryRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Logger/LogEntryRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Payment/GroupRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Payment/PaymentRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Travel/CommandRepositoryTest.php
  tests/integration/Infrastructure/Repositories/Travel/ContractRepositoryTest.php
  tests/integration/Payment/ReadModel/QueryHandlers/CountGroupsWithBankAccountQueryHandlerTest.php
  tests/integration/Payment/ReadModel/QueryHandlers/PairedPaymentsQueryHandlerTest.php
Labels: Refactoring

#1612 fix access denied rendering
  app/AccountancyModule/CampModule/presenters/BasePresenter.php
  app/AccountancyModule/EventModule/presenters/BasePresenter.php
Labels: PR - Bugfix
